### PR TITLE
Try out jekyll-title

### LINKED ISSUE #36: Need Liquid filter for "title" case.
Sample:

THIS IS A TITLE

would convert to 

This Is A Title

using the following format:
`{{ page.title | title }}`

### PR DESCRIPTION
**Pull request by gregoryjscott**
This branch can be used to test out a jekyll-title gem. This will close #36 when completed.

Todo
- [x] Create jekyll-title repository on cityoffortworth
- [x] Change Gemfile to point to cityoffortworth
- [x] Remove changes from testing

### CODE REVIEW

**Comment by gregoryjscott** [comment]
@bechatman give this a look when you get a chance.

**Comment by bechatman** [comment]
Looks good to me.

**Comment by bechatman** [comment]
@gregoryjscott When do you think we will be able to launch this and the ap plugin? Now that the Roundup calendar and the Purchasing pages are up, I would like to get these filters on the display.

**Comment by gregoryjscott** [comment]
@bechatman Can you go ahead and create the cityoffortworth repos for the new gems (see the first task on this PR and #81) and give me access? Sorry, I should have assigned the PRs to you. I can finish it up pretty quick after that.

**Pull request merged**
