### PR TITLE
Try out the before and after filters in the gem

### PR DESCRIPTION
**Pull request by gregoryjscott**
This branch should let you experiment with the version of jekyll-date_logic gem that contains `before` and `after` filters.

### CODE REVIEW

**Comment by bechatman** [comment]
I am getting this error: 

```
Liquid Exception: no implicit conversion of nil into String in codecompliance/keep-fort-worth-beautiful/kfwb-home.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/time.rb:325:in `_parse': no implicit conversion of nil into String (TypeError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/time.rb:325:in `parse'
	from /Users/chatmab/.bundler/ruby/2.0.0/jekyll-date_logic-fbfc75d59a3d/lib/jekyll/date_logic/before_filter.rb:18:in `parse_time'
	from /Users/chatmab/.bundler/ruby/2.0.0/jekyll-date_logic-fbfc75d59a3d/lib/jekyll/date_logic/before_filter.rb:9:in `block in before'
	from /Users/chatmab/.bundler/ruby/2.0.0/jekyll-date_logic-fbfc75d59a3d/lib/jekyll/date_logic/before_filter.rb:8:in `select'
	from /Users/chatmab/.bundler/ruby/2.0.0/jekyll-date_logic-fbfc75d59a3d/lib/jekyll/date_logic/before_filter.rb:8:in `before'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/strainer.rb:43:in `invoke'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/context.rb:82:in `invoke'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/variable.rb:50:in `block in render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/variable.rb:38:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/variable.rb:38:in `inject'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/variable.rb:38:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/tags/assign.rb:26:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:233:in `do_layout'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/page.rb:122:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
```

**Comment by gregoryjscott** [comment]
Can you push your changes to this branch that expose the problem?

**Comment by bechatman** [comment]
Just sent it up. I only used one filter to keep things simple.

**Comment by gregoryjscott** [comment]
I removed the hundreds of lines in that .csv file that only contain commas and it builds now. How should the array filters behave when the data doesn't contain data for the field that is passed (`end_date` in this case)? Should it throw an error, remove the row, or keep the row?

**Comment by bechatman** [comment]
I think we just let it pass through. There is already a nils value on sort, so i can use that to handle issues where i am sorting on something i am filtering. The hundreds of lines of blank rows is just whay excel does. Windows version is worse, but it has been doing that on brand new files. I think it is rendering anything visible in the viewport to the file because it doesnt happen on long files.

**Comment by gregoryjscott** [comment]
OK, it lets it pass through now. Basically the `before` block and `before` filter treat null dates the same way - it lets the data/content pass through and outputs a warning. `after` works the same way. So you'll get a lot of warnings, but I hate to just ignore this situation quietly. You might want to know when your data is missing a field.

**Comment by bechatman** [comment]
Yeah it is useful. I just wish that the warning could say which page threw the error (and the line number). Should I test and merge this branch or is there still more to do?

**Comment by gregoryjscott** [comment]
I'll do a new PR that just updates the gem.

**Pull request closed without merging**
