### PR TITLE
Rollout archive pages and feature widgets

### LINKED ISSUE #33: Create 'feature' and 'ad' data resource
This feature is dependent on date logic being added. To avoid additional pages to render, this content will be editable via a CSV or YAML document in _data.

### PR DESCRIPTION
**Pull request by bechatman**
This request will close #33.

### CODE REVIEW

**Comment by bechatman** [comment]
@gregoryjscott I put a plugin in the feature-test branch that would automatically generate archive pages, but I ran into a couple of issues. 

* When I changed the format for the article entries, the date does not appear. From what I can tell, the date isn't added to the file correctly ... or that early in the ruby file. 
* My year-based archive pages that I wanted to create to link to the monthly pages dynamically also cannot filter by date or output date information based on the plug-in-generated pages.
* I tried to reformat the archive page names to be just spelled out month and year (January 2015, for example), but I didn't see a good way to accomplish this. 

If you have a way to fix those issues, I can create the necessary year-based archive pages, but if you know of a way to generate this format from the plugin as well, that would be great, too.

**Comment by gregoryjscott** [comment]
But it doesn't appear to be working. Ugh! I'm working on it.

**Comment by gregoryjscott** [comment]
OK, I think it works like you want it to now. I switched the index page to use `before item.date for_hours=216`. It will now show calendar items for 216 hours before their date.

**Comment by bechatman** [comment]
Well I am trying to do a build, but it won't let me without running `bundle install` and it isn't connecting to the repo for date logic. Is it building for you?

**Comment by bechatman** [comment]
Ignore my last comment... I think it was a connection issue.

**Comment by bechatman** [comment]
Or you made the change and I just happened to build at the exact time.

**Comment by gregoryjscott** [comment]
It works both ways for me but https is probably better so let's leave it.

**Pull request merged**
